
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 21 16:03:21 BST 2013
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 20;
  public static final int STRING_LITERAL = 8;
  public static final int POWER = 21;
  public static final int CHAR = 9;
  public static final int CONCAT = 46;
  public static final int LPAREN = 27;
  public static final int GREATER = 15;
  public static final int SEMI = 25;
  public static final int REPEAT = 44;
  public static final int INT = 7;
  public static final int LESS = 13;
  public static final int MINUS = 18;
  public static final int RPAREN = 28;
  public static final int NOT = 22;
  public static final int AND = 24;
  public static final int LTUPLE = 47;
  public static final int TYPE = 3;
  public static final int IN = 39;
  public static final int TDEF = 36;
  public static final int OR = 23;
  public static final int BOOL = 5;
  public static final int RSQPAREN = 32;
  public static final int COMMA = 33;
  public static final int UNTIL = 45;
  public static final int PLUS = 17;
  public static final int RTUPLE = 48;
  public static final int IF = 40;
  public static final int DOT = 35;
  public static final int ID = 2;
  public static final int GREATEROREQ = 16;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int error = 1;
  public static final int FDEF = 37;
  public static final int VOID = 4;
  public static final int EQ = 10;
  public static final int TIMES = 19;
  public static final int COLON = 26;
  public static final int ELSE = 41;
  public static final int LBRACE = 29;
  public static final int WHILE = 43;
  public static final int FLOAT = 6;
  public static final int EQCOMP = 12;
  public static final int LESSOREQ = 14;
  public static final int RBRACE = 30;
  public static final int LEN = 34;
  public static final int LSQPAREN = 31;
  public static final int DO = 42;
  public static final int NOTEQ = 11;

  /* non terminals */
  static final int funcBlockStmt = 12;
  static final int typeSpecifier = 2;
  static final int functionDecl = 3;
  static final int expr = 20;
  static final int functionDeclVoid = 4;
  static final int variableDecl = 6;
  static final int mainStmtNoFollowingSubstmt = 19;
  static final int fieldDecl = 9;
  static final int functionDeclReturn = 5;
  static final int program = 0;
  static final int sequence = 23;
  static final int funcStmtNoFollowingSubstmt = 17;
  static final int sequenceOptional = 24;
  static final int funcStmtList = 11;
  static final int mainBlockStmt = 14;
  static final int mainStmt = 18;
  static final int typeDecl = 7;
  static final int funcStmt = 16;
  static final int returnStmt = 15;
  static final int value = 22;
  static final int declList = 1;
  static final int fcall = 21;
  static final int mainStmtList = 13;
  static final int mainDecl = 8;
  static final int fieldDeclOptional = 10;
}

