
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 14 17:01:21 GMT 2013
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 16;
  public static final int STRING_LITERAL = 32;
  public static final int POWER = 17;
  public static final int CHAR = 33;
  public static final int LPAREN = 24;
  public static final int GREATER = 11;
  public static final int SEMI = 21;
  public static final int REPEAT = 43;
  public static final int INT = 5;
  public static final int LESS = 9;
  public static final int MINUS = 14;
  public static final int RPAREN = 25;
  public static final int NOT = 18;
  public static final int AND = 20;
  public static final int TYPE = 22;
  public static final int OR = 19;
  public static final int TDEF = 34;
  public static final int BOOL = 3;
  public static final int RSQPAREN = 29;
  public static final int COMMA = 30;
  public static final int UNTIL = 44;
  public static final int PLUS = 13;
  public static final int IF = 39;
  public static final int ID = 2;
  public static final int GREATEROREQ = 12;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int TEST = 37;
  public static final int error = 1;
  public static final int PIPE = 31;
  public static final int FDEF = 35;
  public static final int VOID = 36;
  public static final int EQ = 6;
  public static final int TIMES = 15;
  public static final int COLON = 23;
  public static final int ELSE = 40;
  public static final int LBRACE = 26;
  public static final int WHILE = 42;
  public static final int FLOAT = 4;
  public static final int EQCOMP = 8;
  public static final int LESSOREQ = 10;
  public static final int RBRACE = 27;
  public static final int LSQPAREN = 28;
  public static final int DO = 41;
  public static final int NOTEQ = 7;

  /* non terminals */
  static final int type_specifier = 12;
  static final int statement = 15;
  static final int newDT = 11;
  static final int functionDecl = 13;
  static final int expr = 17;
  static final int variableDecl = 2;
  static final int simpleInit = 5;
  static final int fieldDecl = 7;
  static final int program = 0;
  static final int fbody = 14;
  static final int tuple = 6;
  static final int statementList = 16;
  static final int typeDecl = 8;
  static final int typeDeclList = 9;
  static final int initalisation = 3;
  static final int variableDeclList = 10;
  static final int grammar = 1;
  static final int list = 4;
}

