/* The following code was generated by JFlex 1.4.3 on 3/14/13 5:06 PM */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/14/13 5:06 PM from the specification file
 * <tt>C:/Users/EmilGeorge/Dropbox/Compilers/Compilers/Q.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\3\1\23\1\22\1\0\1\23\1\66\16\3\4\0\1\23\1\41"+
    "\1\61\1\0\1\3\1\0\1\51\1\34\1\54\1\55\1\45\1\44"+
    "\1\60\1\5\1\0\1\46\1\4\11\1\1\37\1\36\1\42\1\40"+
    "\1\43\2\0\3\35\1\21\4\35\1\20\5\35\1\17\6\35\1\16"+
    "\4\35\1\52\1\65\1\53\1\47\1\3\1\0\1\13\1\30\1\32"+
    "\1\62\1\11\1\12\1\31\1\33\1\24\2\2\1\14\1\2\1\25"+
    "\1\26\1\27\1\2\1\7\1\15\1\6\1\10\1\2\1\63\1\64"+
    "\2\2\1\56\1\50\1\57\1\0\41\3\2\0\4\3\4\0\1\3"+
    "\2\0\1\3\7\0\1\3\4\0\1\3\5\0\27\3\1\0\37\3"+
    "\1\0\u01ca\3\4\0\14\3\16\0\5\3\7\0\1\3\1\0\1\3"+
    "\21\0\165\3\1\0\2\3\2\0\4\3\10\0\1\3\1\0\3\3"+
    "\1\0\1\3\1\0\24\3\1\0\123\3\1\0\213\3\1\0\5\3"+
    "\2\0\236\3\11\0\46\3\2\0\1\3\7\0\47\3\11\0\55\3"+
    "\1\0\1\3\1\0\2\3\1\0\2\3\1\0\1\3\10\0\33\3"+
    "\5\0\3\3\15\0\4\3\7\0\1\3\4\0\13\3\5\0\112\3"+
    "\4\0\146\3\1\0\11\3\1\0\12\3\1\0\23\3\2\0\1\3"+
    "\17\0\74\3\2\0\145\3\16\0\66\3\4\0\1\3\5\0\56\3"+
    "\22\0\34\3\244\0\144\3\2\0\12\3\1\0\7\3\1\0\7\3"+
    "\1\0\3\3\1\0\10\3\2\0\2\3\2\0\26\3\1\0\7\3"+
    "\1\0\1\3\3\0\4\3\2\0\11\3\2\0\2\3\2\0\4\3"+
    "\10\0\1\3\4\0\2\3\1\0\5\3\2\0\16\3\7\0\1\3"+
    "\5\0\3\3\1\0\6\3\4\0\2\3\2\0\26\3\1\0\7\3"+
    "\1\0\2\3\1\0\2\3\1\0\2\3\2\0\1\3\1\0\5\3"+
    "\4\0\2\3\2\0\3\3\3\0\1\3\7\0\4\3\1\0\1\3"+
    "\7\0\20\3\13\0\3\3\1\0\11\3\1\0\3\3\1\0\26\3"+
    "\1\0\7\3\1\0\2\3\1\0\5\3\2\0\12\3\1\0\3\3"+
    "\1\0\3\3\2\0\1\3\17\0\4\3\2\0\12\3\1\0\1\3"+
    "\17\0\3\3\1\0\10\3\2\0\2\3\2\0\26\3\1\0\7\3"+
    "\1\0\2\3\1\0\5\3\2\0\11\3\2\0\2\3\2\0\3\3"+
    "\10\0\2\3\4\0\2\3\1\0\5\3\2\0\12\3\1\0\1\3"+
    "\20\0\2\3\1\0\6\3\3\0\3\3\1\0\4\3\3\0\2\3"+
    "\1\0\1\3\1\0\2\3\3\0\2\3\3\0\3\3\3\0\14\3"+
    "\4\0\5\3\3\0\3\3\1\0\4\3\2\0\1\3\6\0\1\3"+
    "\16\0\12\3\11\0\1\3\7\0\3\3\1\0\10\3\1\0\3\3"+
    "\1\0\27\3\1\0\12\3\1\0\5\3\3\0\10\3\1\0\3\3"+
    "\1\0\4\3\7\0\2\3\1\0\2\3\6\0\4\3\2\0\12\3"+
    "\22\0\2\3\1\0\10\3\1\0\3\3\1\0\27\3\1\0\12\3"+
    "\1\0\5\3\2\0\11\3\1\0\3\3\1\0\4\3\7\0\2\3"+
    "\7\0\1\3\1\0\4\3\2\0\12\3\1\0\2\3\17\0\2\3"+
    "\1\0\10\3\1\0\3\3\1\0\51\3\2\0\10\3\1\0\3\3"+
    "\1\0\5\3\10\0\1\3\10\0\4\3\2\0\12\3\12\0\6\3"+
    "\2\0\2\3\1\0\22\3\3\0\30\3\1\0\11\3\1\0\1\3"+
    "\2\0\7\3\3\0\1\3\4\0\6\3\1\0\1\3\1\0\10\3"+
    "\22\0\2\3\15\0\72\3\4\0\20\3\1\0\12\3\47\0\2\3"+
    "\1\0\1\3\2\0\2\3\1\0\1\3\2\0\1\3\6\0\4\3"+
    "\1\0\7\3\1\0\3\3\1\0\1\3\1\0\1\3\2\0\2\3"+
    "\1\0\15\3\1\0\3\3\2\0\5\3\1\0\1\3\1\0\6\3"+
    "\2\0\12\3\2\0\2\3\42\0\1\3\27\0\2\3\6\0\12\3"+
    "\13\0\1\3\1\0\1\3\1\0\1\3\4\0\12\3\1\0\44\3"+
    "\4\0\24\3\1\0\22\3\1\0\44\3\11\0\1\3\71\0\112\3"+
    "\6\0\116\3\2\0\46\3\12\0\53\3\1\0\1\3\3\0\u0149\3"+
    "\1\0\4\3\2\0\7\3\1\0\1\3\1\0\4\3\2\0\51\3"+
    "\1\0\4\3\2\0\41\3\1\0\4\3\2\0\7\3\1\0\1\3"+
    "\1\0\4\3\2\0\17\3\1\0\71\3\1\0\4\3\2\0\103\3"+
    "\2\0\3\3\40\0\20\3\20\0\125\3\14\0\u026c\3\2\0\21\3"+
    "\1\0\32\3\5\0\113\3\3\0\3\3\17\0\15\3\1\0\7\3"+
    "\13\0\25\3\13\0\24\3\14\0\15\3\1\0\3\3\1\0\2\3"+
    "\14\0\124\3\3\0\1\3\3\0\3\3\2\0\12\3\41\0\3\3"+
    "\2\0\12\3\6\0\130\3\10\0\53\3\5\0\106\3\12\0\35\3"+
    "\3\0\14\3\4\0\14\3\12\0\50\3\2\0\5\3\13\0\54\3"+
    "\4\0\32\3\6\0\12\3\46\0\34\3\4\0\77\3\1\0\35\3"+
    "\2\0\13\3\6\0\12\3\15\0\1\3\130\0\114\3\4\0\12\3"+
    "\21\0\11\3\14\0\53\3\3\0\14\3\6\0\64\3\14\0\70\3"+
    "\10\0\12\3\3\0\61\3\122\0\3\3\1\0\37\3\15\0\347\3"+
    "\25\0\u011a\3\2\0\6\3\2\0\46\3\2\0\6\3\2\0\10\3"+
    "\1\0\1\3\1\0\1\3\1\0\1\3\1\0\37\3\2\0\65\3"+
    "\1\0\7\3\1\0\1\3\3\0\3\3\1\0\7\3\3\0\4\3"+
    "\2\0\6\3\4\0\15\3\5\0\3\3\1\0\7\3\16\0\5\3"+
    "\32\0\5\3\20\0\2\3\23\0\1\3\13\0\5\3\5\0\6\3"+
    "\1\0\1\3\15\0\1\3\20\0\15\3\3\0\32\3\26\0\15\3"+
    "\4\0\1\3\3\0\14\3\21\0\1\3\4\0\1\3\2\0\12\3"+
    "\1\0\1\3\3\0\5\3\6\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\4\3\1\0\13\3\2\0\4\3\5\0\5\3\4\0\1\3"+
    "\21\0\51\3\u0a77\0\57\3\1\0\57\3\1\0\205\3\6\0\7\3"+
    "\16\0\46\3\12\0\66\3\11\0\1\3\17\0\30\3\11\0\7\3"+
    "\1\0\7\3\1\0\7\3\1\0\7\3\1\0\7\3\1\0\7\3"+
    "\1\0\7\3\1\0\7\3\1\0\40\3\57\0\1\3\u01d5\0\3\3"+
    "\31\0\17\3\1\0\5\3\2\0\5\3\4\0\126\3\2\0\2\3"+
    "\2\0\3\3\1\0\132\3\1\0\4\3\5\0\51\3\3\0\136\3"+
    "\21\0\33\3\65\0\20\3\u0200\0\u19b6\3\112\0\u51cc\3\64\0\u048d\3"+
    "\103\0\56\3\2\0\u010d\3\3\0\34\3\24\0\60\3\14\0\2\3"+
    "\1\0\31\3\10\0\122\3\45\0\11\3\2\0\147\3\2\0\4\3"+
    "\1\0\2\3\16\0\12\3\120\0\56\3\20\0\1\3\7\0\64\3"+
    "\14\0\105\3\13\0\12\3\6\0\30\3\3\0\1\3\4\0\56\3"+
    "\2\0\44\3\14\0\35\3\3\0\101\3\16\0\13\3\46\0\67\3"+
    "\11\0\16\3\2\0\12\3\6\0\27\3\3\0\2\3\4\0\103\3"+
    "\30\0\3\3\43\0\6\3\2\0\6\3\2\0\6\3\11\0\7\3"+
    "\1\0\7\3\221\0\53\3\1\0\2\3\2\0\12\3\6\0\u2ba4\3"+
    "\14\0\27\3\4\0\61\3\u2104\0\u012e\3\2\0\76\3\2\0\152\3"+
    "\46\0\7\3\14\0\5\3\5\0\14\3\1\0\15\3\1\0\5\3"+
    "\1\0\1\3\1\0\2\3\1\0\2\3\1\0\154\3\41\0\u016b\3"+
    "\22\0\100\3\2\0\66\3\50\0\15\3\3\0\20\3\20\0\7\3"+
    "\14\0\2\3\30\0\3\3\31\0\1\3\6\0\5\3\1\0\207\3"+
    "\2\0\1\3\4\0\1\3\13\0\12\3\7\0\32\3\4\0\1\3"+
    "\1\0\32\3\13\0\131\3\3\0\6\3\2\0\6\3\2\0\6\3"+
    "\2\0\3\3\3\0\2\3\3\0\2\3\22\0\3\3\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\2\1\4\7\3\1\1"+
    "\1\5\3\3\1\1\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\1\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\2\3"+
    "\1\31\1\32\1\33\3\0\14\3\1\0\1\34\3\3"+
    "\1\0\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\3\1\44\1\45\1\46\1\47\2\50\14\3\1\0"+
    "\1\51\2\3\1\52\1\3\1\53\2\3\1\54\3\3"+
    "\1\55\1\56\1\3\1\57\4\3\1\60\1\3\1\61"+
    "\1\3\1\62\1\63\1\3\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\156"+
    "\0\u0339\0\u0370\0\u03a7\0\u03de\0\156\0\156\0\u0415\0\u044c"+
    "\0\u0483\0\u04ba\0\156\0\156\0\156\0\156\0\u04f1\0\u0528"+
    "\0\156\0\156\0\156\0\156\0\156\0\156\0\156\0\156"+
    "\0\u055f\0\u0596\0\u05cd\0\156\0\u0604\0\u063b\0\u0672\0\u0113"+
    "\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a"+
    "\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d\0\334\0\u0974\0\u09ab"+
    "\0\u09e2\0\u0a19\0\156\0\156\0\156\0\156\0\156\0\156"+
    "\0\334\0\u0a50\0\156\0\156\0\156\0\156\0\u063b\0\u0672"+
    "\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08"+
    "\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\334\0\u0d52\0\u0d89"+
    "\0\156\0\u0dc0\0\334\0\u0df7\0\u0e2e\0\334\0\u0e65\0\u0e9c"+
    "\0\u0ed3\0\334\0\334\0\u0f0a\0\156\0\u0f41\0\u0f78\0\u0faf"+
    "\0\u0fe6\0\334\0\u101d\0\334\0\u1054\0\334\0\334\0\u108b"+
    "\0\334";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\5\1\15\1\16\1\17\3\3"+
    "\2\20\1\21\3\5\1\22\1\5\1\23\1\5\1\24"+
    "\1\3\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\5"+
    "\1\3\1\20\22\53\1\0\36\53\1\54\3\53\1\55"+
    "\70\0\1\56\1\4\2\56\1\4\15\56\1\0\44\56"+
    "\1\0\4\5\1\0\14\5\2\0\10\5\1\0\1\5"+
    "\24\0\3\5\2\0\1\56\1\57\2\56\1\57\15\56"+
    "\1\0\44\56\1\0\1\4\2\0\1\60\63\0\4\5"+
    "\1\0\1\5\1\61\1\62\1\63\10\5\2\0\10\5"+
    "\1\0\1\5\24\0\1\64\2\5\3\0\4\5\1\0"+
    "\3\5\1\65\10\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\14\5\2\0\1\5\1\66"+
    "\6\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\6\5\1\67\5\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\5\5\1\70\1\71\5\5"+
    "\2\0\10\5\1\0\1\5\24\0\1\72\2\5\3\0"+
    "\4\5\1\0\14\5\2\0\1\73\7\5\1\0\1\5"+
    "\24\0\3\5\3\0\4\5\1\0\1\74\13\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\21\0\1\75\50\0"+
    "\4\5\1\0\4\5\1\76\7\5\2\0\1\5\1\77"+
    "\6\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\14\5\2\0\2\5\1\100\5\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\14\5\2\0\7\5\1\101"+
    "\1\0\1\5\24\0\3\5\3\0\2\102\1\0\1\102"+
    "\1\0\14\102\2\0\10\102\1\0\1\102\24\0\3\102"+
    "\42\0\1\103\66\0\1\104\66\0\1\105\66\0\1\106"+
    "\76\0\1\107\67\0\1\110\16\0\4\5\1\0\14\5"+
    "\2\0\2\5\1\111\5\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\14\5\2\0\7\5\1\112\1\0"+
    "\1\5\24\0\3\5\2\0\22\53\1\0\36\53\1\0"+
    "\3\53\10\0\1\113\1\114\15\0\1\115\33\0\1\116"+
    "\6\0\1\117\2\0\1\117\62\0\1\56\1\120\2\56"+
    "\1\120\15\56\1\0\44\56\1\0\4\5\1\0\2\5"+
    "\1\121\11\5\2\0\10\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\14\5\2\0\3\5\1\122\4\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\7\5"+
    "\1\123\4\5\2\0\10\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\3\5\1\124\10\5\2\0\10\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\1\125"+
    "\13\5\2\0\3\5\1\126\4\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\1\127\13\5\2\0\10\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\7\5"+
    "\1\130\4\5\2\0\10\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\6\5\1\131\5\5\2\0\10\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\14\5"+
    "\2\0\2\5\1\132\5\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\3\5\1\133\10\5\2\0\10\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\7\5"+
    "\1\77\4\5\2\0\10\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\1\5\1\134\12\5\2\0\10\5"+
    "\1\0\1\5\24\0\3\5\22\0\1\135\47\0\4\5"+
    "\1\0\1\136\13\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\14\5\2\0\2\5\1\137"+
    "\5\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\5\5\1\140\6\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\36\0\1\141\33\0\4\5\1\0\14\5\2\0"+
    "\1\142\7\5\1\0\1\5\24\0\3\5\3\0\4\5"+
    "\1\0\3\5\1\143\10\5\2\0\10\5\1\0\1\5"+
    "\24\0\3\5\3\0\4\5\1\0\6\5\1\144\5\5"+
    "\2\0\10\5\1\0\1\5\24\0\3\5\3\0\4\5"+
    "\1\0\1\145\13\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\4\5\1\146\7\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\2\5\1\147\11\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\3\5\1\150\10\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\14\5\2\0\1\151\7\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\3\5\1\152\10\5\2\0\10\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\7\5"+
    "\1\121\4\5\2\0\10\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\5\5\1\77\6\5\2\0\10\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\4\5"+
    "\1\153\7\5\2\0\10\5\1\0\1\5\24\0\3\5"+
    "\3\0\4\5\1\0\14\5\2\0\1\154\7\5\1\0"+
    "\1\5\24\0\3\5\23\0\1\155\46\0\4\5\1\0"+
    "\6\5\1\136\5\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\1\5\1\136\12\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\6\5\1\156\5\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\3\5\1\136\10\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\3\5\1\157\10\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\1\5\1\160\12\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\5\5\1\161\6\5\2\0\10\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\6\5\1\162\5\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\14\5\2\0\1\5\1\163\6\5\1\0\1\5\24\0"+
    "\3\5\3\0\4\5\1\0\3\5\1\164\10\5\2\0"+
    "\10\5\1\0\1\5\24\0\3\5\3\0\4\5\1\0"+
    "\14\5\2\0\10\5\1\0\1\5\24\0\2\5\1\165"+
    "\3\0\4\5\1\0\14\5\2\0\1\5\1\166\6\5"+
    "\1\0\1\5\24\0\3\5\3\0\4\5\1\0\1\167"+
    "\13\5\2\0\10\5\1\0\1\5\24\0\3\5\3\0"+
    "\4\5\1\0\14\5\2\0\5\5\1\136\2\5\1\0"+
    "\1\5\24\0\3\5\3\0\4\5\1\0\14\5\2\0"+
    "\3\5\1\170\4\5\1\0\1\5\24\0\3\5\3\0"+
    "\4\5\1\0\1\5\1\171\12\5\2\0\10\5\1\0"+
    "\1\5\24\0\3\5\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4290];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\14\1\1\11\4\1\2\11\4\1\4\11"+
    "\2\1\10\11\3\1\1\11\1\1\3\0\14\1\1\0"+
    "\4\1\1\0\6\11\2\1\4\11\16\1\1\0\3\1"+
    "\1\11\13\1\1\11\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[121];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
    private Symbol symbol(int type) { 
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }
  
  public int getLineNumber() { return yyline + 1; }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1918) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [59] { return symbol(sym.RPAREN); }");
          { return symbol(sym.RPAREN);
          }
        case 53: break;
        case 36: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [92] { string.append(\'\\t\'); }");
          { string.append('\t');
          }
        case 54: break;
        case 17: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [56] { return symbol(sym.LSQPAREN); }");
          { return symbol(sym.LSQPAREN);
          }
        case 55: break;
        case 21: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [60] { return symbol(sym.LBRACE); }");
          { return symbol(sym.LBRACE);
          }
        case 56: break;
        case 24: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [64] { string.setLength(0); yybegin(STRING); }");
          { string.setLength(0); yybegin(STRING);
          }
        case 57: break;
        case 31: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [45] { return symbol(sym.LESSOREQ); }");
          { return symbol(sym.LESSOREQ);
          }
        case 58: break;
        case 9: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [53] { return symbol(sym.NOT); }");
          { return symbol(sym.NOT);
          }
        case 59: break;
        case 34: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [55] { return symbol(sym.AND); }");
          { return symbol(sym.AND);
          }
        case 60: break;
        case 27: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [97] { string.append(\'\\\\\'); }");
          { string.append('\\');
          }
        case 61: break;
        case 50: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [65] { return symbol(sym.RETURN); }");
          { return symbol(sym.RETURN);
          }
        case 62: break;
        case 46: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [74] { return symbol(sym.FDEF); }");
          { return symbol(sym.FDEF);
          }
        case 63: break;
        case 37: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [95] { string.append(\'\\r\'); }");
          { string.append('\r');
          }
        case 64: break;
        case 12: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [48] { return symbol(sym.PLUS); }");
          { return symbol(sym.PLUS);
          }
        case 65: break;
        case 26: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [88] { yybegin(YYINITIAL); "+ZZ_NL+"                                   return symbol(sym.STRING_LITERAL, "+ZZ_NL+"                                   string.toString()); }");
          { yybegin(YYINITIAL); 
                                   return symbol(sym.STRING_LITERAL, 
                                   string.toString());
          }
        case 66: break;
        case 10: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [44] { return symbol(sym.LESS); }");
          { return symbol(sym.LESS);
          }
        case 67: break;
        case 52: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [72] { return symbol(sym.TEST); }");
          { return symbol(sym.TEST);
          }
        case 68: break;
        case 43: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [76] { return symbol(sym.BOOL, new Boolean(yytext())); }");
          { return symbol(sym.BOOL, new Boolean(yytext()));
          }
        case 69: break;
        case 18: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [57] { return symbol(sym.RSQPAREN); }");
          { return symbol(sym.RSQPAREN);
          }
        case 70: break;
        case 41: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [38] { return symbol(sym.TYPE); }");
          { return symbol(sym.TYPE);
          }
        case 71: break;
        case 47: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [81] { return symbol(sym.VOID); }");
          { return symbol(sym.VOID);
          }
        case 72: break;
        case 35: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [68] { return symbol(sym.DO); }");
          { return symbol(sym.DO);
          }
        case 73: break;
        case 13: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [50] { return symbol(sym.TIMES); }");
          { return symbol(sym.TIMES);
          }
        case 74: break;
        case 1: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [82] { System.err.println(\"Illegal character <\"+"+ZZ_NL+"                                                    yytext()+\">\"); }");
          { System.err.println("Illegal character <"+
                                                    yytext()+">");
          }
        case 75: break;
        case 2: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [78] { return symbol(sym.INT, new Integer(yytext())); }");
          { return symbol(sym.INT, new Integer(yytext()));
          }
        case 76: break;
        case 45: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [67] { return symbol(sym.ELSE); }");
          { return symbol(sym.ELSE);
          }
        case 77: break;
        case 39: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [96] { string.append(\'\\\"\'); }");
          { string.append('\"');
          }
        case 78: break;
        case 7: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [40] { return symbol(sym.COLON); }");
          { return symbol(sym.COLON);
          }
        case 79: break;
        case 11: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [46] { return symbol(sym.GREATER); }");
          { return symbol(sym.GREATER);
          }
        case 80: break;
        case 49: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [69] { return symbol(sym.WHILE); }");
          { return symbol(sym.WHILE);
          }
        case 81: break;
        case 44: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [73] { return symbol(sym.TDEF); }");
          { return symbol(sym.TDEF);
          }
        case 82: break;
        case 28: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [66] { return symbol(sym.IF); }");
          { return symbol(sym.IF);
          }
        case 83: break;
        case 19: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [58] { return symbol(sym.LPAREN); }");
          { return symbol(sym.LPAREN);
          }
        case 84: break;
        case 48: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [71] { return symbol(sym.UNTIL); }");
          { return symbol(sym.UNTIL);
          }
        case 85: break;
        case 33: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [54] { return symbol(sym.OR); }");
          { return symbol(sym.OR);
          }
        case 86: break;
        case 8: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [41] { return symbol(sym.EQ); }");
          { return symbol(sym.EQ);
          }
        case 87: break;
        case 22: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [61] { return symbol(sym.RBRACE); }");
          { return symbol(sym.RBRACE);
          }
        case 88: break;
        case 40: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [79] { return symbol(sym.FLOAT, new Float(yytext())); }");
          { return symbol(sym.FLOAT, new Float(yytext()));
          }
        case 89: break;
        case 38: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [93] { string.append(\'\\n\'); }");
          { string.append('\n');
          }
        case 90: break;
        case 6: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [39] { return symbol(sym.SEMI); }");
          { return symbol(sym.SEMI);
          }
        case 91: break;
        case 4: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [49] { return symbol(sym.MINUS); }");
          { return symbol(sym.MINUS);
          }
        case 92: break;
        case 16: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [63] { return symbol(sym.PIPE); }");
          { return symbol(sym.PIPE);
          }
        case 93: break;
        case 3: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [77] { return symbol(sym.ID); }");
          { return symbol(sym.ID);
          }
        case 94: break;
        case 32: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [47] { return symbol(sym.GREATEROREQ); }");
          { return symbol(sym.GREATEROREQ);
          }
        case 95: break;
        case 42: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [75] { return symbol(sym.CHAR, yytext()); }");
          { return symbol(sym.CHAR, yytext());
          }
        case 96: break;
        case 14: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [51] { return symbol(sym.DIVIDE); }");
          { return symbol(sym.DIVIDE);
          }
        case 97: break;
        case 30: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [43] { return symbol(sym.NOTEQ); }");
          { return symbol(sym.NOTEQ);
          }
        case 98: break;
        case 23: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [62] { return symbol(sym.COMMA); }");
          { return symbol(sym.COMMA);
          }
        case 99: break;
        case 29: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [42] { return symbol(sym.EQCOMP); }");
          { return symbol(sym.EQCOMP);
          }
        case 100: break;
        case 25: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [91] { string.append( yytext() ); }");
          { string.append( yytext() );
          }
        case 101: break;
        case 15: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [52] { return symbol(sym.POWER); }");
          { return symbol(sym.POWER);
          }
        case 102: break;
        case 51: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [70] { return symbol(sym.REPEAT); }");
          { return symbol(sym.REPEAT);
          }
        case 103: break;
        case 5: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [80] {  }");
          { 
          }
        case 104: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Yylex <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Yylex scanner = null;
        try {
          scanner = new Yylex( new java.io.FileReader(argv[i]) );
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
